Fix Bruno Ferraz info and image
Hackathonners/website pull request #5
Opened 2017-12-15 22:55 UTC by bmaferraz

I updated my info and my image

2017-12-17 13:46 UTC, fntneves requested changes
Please change your github link.

2017-12-17 13:46 UTC, fntneves commented on index.html
>                                  <a target="_blank" href="https://github.com/brunomaf">
This is still using the old username.

2017-12-17 13:46 UTC, fntneves commented on index.html
>                                          <a target="_blank" href="https://twitter.com/bmaf_bm"><i class="fa fa-twitter"></i></a>
Are you going to change Twitter also?

2017-12-18 23:35 UTC, bmaferraz commented
@fntneves I updated all links. And changed my twitter username according other links.

2017-12-20 22:31 UTC, fntneves approved these changes

2017-12-20 22:31 UTC, merged